### ISSUE TITLE
use a custom httpclient instead of http.DefaultClient to add a timeout

### ISSUE THREAD

**Issue by tristangio** [mattevans/pwned-passwords#1]
I just read, Troy Hunt blog post about Pwned Passwords, wanted to use it and saw your lib : great job you will save me time.
However I did some code review and saw you are using http.DefaultClient as http client : be careful that DefaultClient has no timeout by default so it make your lib dependant on https://api.pwnedpasswords.com server response. Although pwnedpassword is a well backed API and it will not hang request every day I think it's preferable to avoid the risk and use a custom http.client just to set a timeout.
See [this](https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779) and [cloudflare guide to timeout](https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/).

I suggest a 3 minutes timeout, because this is the value that may be added to the http.DefaultClient in [future Go release](https://github.com/golang/go/issues/22982)
... or maybe add the possibility to pass the wanted timeout value to hibp.NewClient()

**Comment by mattevans** [comment]
Hi @tristangio,

Thanks for pointing this out. 
I'll be updating this shortly. This was also mentioned as [feedback on reddit](https://www.reddit.com/r/golang/comments/80tv07/go_client_for_checking_values_against_compromised/). I'll keep this issue updated once the change has been made.

**Comment by tristangio** [comment]
Hi, I didn't see the reddit feedback on your work.
I have almost the same remark on the cache. I think cache is good to have but it would be nice if we can disable it and limit it. I have some questions/remarks on it : 
- Expire() is never called, because it's up to user to do it I suppose ?
- Expire() do not use delete() on the map cache (it would implies use of mutex) but it maybe cleaner to limit map index growing in times by deleting element
- ExpireAll() actually is much more a PurgeAll(), I would expect an ExpireAll() to check all map items and remove the expired one from cache
- A limit on cache size is a nice to have (so user can disable cache by setting it to 0)

I don't know if [sync.map](https://medium.com/@deckarep/the-new-kid-in-town-gos-sync-map-de24a6bf7c2c) maybe better to be used as cache, I bet on a map paired with WRmutex ; and if user want another cache method they can still disable the one in your lib and implement another one)

PS: Anyhow this is just remark, for a first throw your library looks good to me (although before using it in production I would set a timeout on request and disable the cache as it is now).
Sorry for my english, it's not my mother tongue

**Comment by mattevans** [comment]
See https://github.com/mattevans/pwned-passwords/releases/tag/v0.5.0. Closing. Thank you.
